### ISSUE TITLE
R en production-Définitions

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/formation-bonnes-pratiques-git-R#20]
Ici :

https://github.com/InseeFrLab/formation-bonnes-pratiques-git-R/blob/0dbe28a536e61f8a6cc6a2bfc09e1d26c0d1344f/slides/_r_advanced.qmd#L126-L128

Je propose de remplacer "déployés" par "maintenus en condition opérationnelle".
Les raisons : 

- dans cette version, on a l'impression que ce n'est qu'une question technique, d'environnement
- il me semble qu'en réalité, c'est surtout organisationnel : qui est responsable de quoi ? donc des moyens humains associés (moyens de la DSI vs. moyens métiers)

**Comment by avouacr** [comment]
D'accord avec l'idée ! J'ai juste peur que la reformulation alourdisse une slide déjà bien chargée, que penses-tu de : 

``` 
- [**Production informatique**]{.orange} : processus maintenus par la [**DSI**]{.blue2} sur des [**infrastructures avec "garantie de service"**]{.blue2} 
- [**Self de production**]{.orange} : processus maintenus par le [**métier**]{.blue2} sur une [**infrastructure "self"**]{.blue2}
 ```

quitte à bien expliquer à l'oral qu'on entend maintenu = MCO ? J'ai aussi rajouté de l'emphase sur DSI/métier pour bien montrer effectivement que ce n'est pas qu'une question d'infra

**Comment by RLesur** [comment]
Oui, très bien
