### ISSUE TITLE
Not just once-tordre le cou au "jetable"

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/formation-bonnes-pratiques-git-R#22]
Une rengaine que j'entends à l'Insee depuis que j'y travaille est que pour certaines opérations comme les études, on fait du "jetable".

Je me demande si dans la partie "Not just once", on ne pourrait pas faire une offensive contre cette idée. En général, quand on me dit que les études c'est du jetable et donc qu'il n'y a pas à se préoccuper de la qualité du process, je réponds : 

- d'expérience, lorsqu'on publie un chiffre, on nous demande toujours à un moment ou à un autre de l'actualiser (pour une étude, ça peut être 1 an, 5 ans ou 10 ans)
- si on ne nous demande pas de le mettre à jour, cela veut dire que le chiffre n'intéresse personne et donc que notre étude ne sert à rien (autrement dit, on bosse dans le vide)

Pour être très honnête, je n'ai réussi à convaincre personne qui ne l'était déjà avec ce raisonnement. Il y a certainement meilleur argumentaire. L'argument du jetable est surtout brandi comme synonyme de flemme ou bien par des personnes qui ne savent pas faire et imaginent que c'est très coûteux de faire du propre.

**Comment by avouacr** [comment]
Entièrement d'accord avec toi. C'est quelque chose que je glisse régulièrement à l'oral, en l’occurrence je pense que j'en aurais parlé ici : 

https://github.com/InseeFrLab/formation-bonnes-pratiques-git-R/blob/0dbe28a536e61f8a6cc6a2bfc09e1d26c0d1344f/slides/_r_advanced.qmd#L215

La raison pour laquelle je n'insiste pas dessus explicitement, c'est que je me dis : si déjà on arrive à gagner l'argument "bon le self en moyenne ça a pas vocation à être tout le temps parfaitement clean, mais par contre quand on a une chaîne de prod il faut que tout ce qu'on dit dans la formation soit appliqué", on sera déjà bien avancés en termes de qualité et on pourra viser plus haut par la suite :)
